GoldenOwlAsia/admin.goldenowl.asia

app/javascript/stylesheets/application/pages/index.scss, app/views/careers/index.html.slim, app/views/devise/registrations/edit.html.slim, app/views/home/index.html.slim, app/views/layouts/application/_nav_bar.html.slim, app/views/posts/index.html.slim, config/locales/simple_form.en.yml
1. Admin Name should be set in the middle of the avatar.
2. Should delete "Welcome" on drop down.
3. Should delete some content. 
4. Should be highlight user when admin's staying user page.
=> fix ui admin detail

Gemfile
=> fix deploy heroku

app/controllers/careers_controller.rb
New Career should be on the top
edit Career.all.order(id: :asc) to Career.all.order(id: :desc)
=> New Career should be on the top

app/models/post.rb, app/serializers/post_serializer.rb, app/views/api/v1/subscriptions/index.html.slim, app/views/devise/registrations/new.html.slim, app/views/home/index.html.slim
- edit table view admin account 
- edit table view subscription
- Do not allow users to create admin accounts
=> edit table admin, subscrip in view, do not allow create new admin account

db/migrate/20200716065118_generate_slugs_for_existing_posts_and_careers.rb, db/schema.rb
- Link to issue:
https://trello.com/c/4TeS8nBw/445-url-link-should-be-replaced-by-seo-url#
- Generate migration slugs for existing posts and careers
=> Generate slugs for existing posts and careers

app/controllers/api/v1/careers_controller.rb, app/controllers/api/v1/posts_controller.rb
=> Fix get objects by slug

app/controllers/api/v1/posts_controller.rb, app/serializers/career_serializer.rb, config/routes.rb
- Fix bug get object by the first id
- Add slug for career serializer
- Edit routes
=> Fix bug get object by the first id, career serializer, routes

app/controllers/api/v1/posts_controller.rb, app/serializers/career_serializer.rb, config/routes.rb
Reverts GoldenOwlAsia/admin.goldenowl.asia#52
=> Revert "Fix bug get object by the first id, career serializer, routes"

app/mailers/subscription_mailer.rb, spec/mailers/subscription_mailer_spec.rb
- Edit sender email
- Edit rspec
=> Edit sender

app/views/layouts/application/_nav_bar.html.slim, app/views/layouts/mailer.html.slim, app/views/subscription_mailer/_signature_email.html.slim, app/views/subscription_mailer/subscribe_email_successfull.html.slim, app/views/subscription_mailer/subscription_email_for_career.html.slim, app/views/subscription_mailer/subscription_email_for_post.html.slim
- https://trello.com/c/0R9fGbT0/453-subscription-email-improve-ui#
- Change font size to 14
- Change h2 title to h3
- User Proxima Nova font
=> Edit email template

app/controllers/api/v1/posts_controller.rb, spec/controllers/api/v1/posts_controller_spec.rb
- Add pagination for index post api
=> Add Pagy to post api

app/controllers/api/v1/posts_controller.rb, app/models/subscription.rb, spec/controllers/api/v1/posts_controller_spec.rb
- Edit render json
- Add associations for career
=> Edit render json, add associations for career

spec/controllers/api/v1/subscriptions_controller_spec.rb
- Remove rspec context not logic
=> Remove rspec context not logic

app/mailers/application_mailer.rb, app/mailers/subscription_mailer.rb
- Change sender name from email to from name
=> Edit sender email

app/serializers/career_serializer.rb
https://trello.com/c/pxgU3L17/462-career-display-error#
- Edit career serializer
=> Edit career serializer

config/settings.yml, spec/mailers/subscription_mailer_spec.rb
- Change blog and career url to production url
=> Change blog and career url to production url

app/views/subscription_mailer/_signature_email.html.slim, app/views/subscription_mailer/subscription_email_for_post.html.slim
- Edit post subscription email content and signature
=> Edit post subscription email content and signature

.env.example, app/controllers/api/v1/posts_controller.rb, spec/controllers/api/v1/posts_controller_spec.rb, spec/factories/job_submissions.rb, spec/models/subscription_spec.rb
**ISSUE**
- Add file env.example
=> add file env.example

config/initializers/mailler.rb
=> fix config send mail

app/controllers/api/v1/post_categories_controller.rb, app/controllers/api/v1/posts_controller.rb, app/controllers/post_categories_controller.rb, app/controllers/posts_controller.rb, app/models/post.rb, app/models/post_category.rb, app/serializers/post_serializer.rb, app/views/layouts/application/_left_menu.html.slim, app/views/post_categories/_form.html.slim, app/views/post_categories/edit.html.slim, app/views/post_categories/index.html.slim, app/views/post_categories/new.html.slim, app/views/post_categories/show.html.slim, app/views/posts/_form.html.slim, app/views/posts/index.html.slim, app/views/posts/show.html.slim, config/routes.rb, db/migrate/20210107023338_create_post_categories.rb, db/migrate/20210107030303_add_post_category_to_posts.rb, db/schema.rb, spec/controllers/api/v1/posts_controller_spec.rb, spec/controllers/posts_controller_spec.rb, spec/factories/job_submissions.rb, spec/factories/post_categories.rb, spec/factories/posts.rb, spec/mailers/subscription_mailer_spec.rb, spec/models/post_spec.rb
ISSUES
https://trello.com/c/BdukJrXu/467-list-of-categories-for-blog
https://trello.com/c/SnUy0m3d/468-search-button-for-blog-page
CHANGES/IMPROVE
- API get list category
- API filter post by category
- API get post by search title and content
SCREENSHOTS
=> Integrate feature search category

app/controllers/api/v1/post_categories_controller.rb
CHANGES/IMPROVE
- Add missing original url function
=> Fix add original url post category

app/controllers/posts_controller.rb, app/models/post.rb, app/serializers/post_serializer.rb, app/views/posts/_form.html.slim, app/views/posts/index.html.slim, app/views/posts/show.html.slim, db/migrate/20210202095307_add_meta_tags_to_posts.rb, db/schema.rb, spec/factories/posts.rb, spec/models/post_spec.rb
CHANGES/IMPROVE
- Add meta tags to posts
SCREENSHOTS
=> Feat add meta tags to posts

app/views/developers/detail.html.slim
**Describe**
- Fix code for detail UI not to break template
- Old UI:
- Already fixed UI:
=> fix: detail-UI

db/migrate/20210704202556_remove_type_from_tech.rb
**Describe**
- Delete no use file
=> update: schema-remove-no-use-file

app/controllers/developers_controller.rb
**Describe**
- Fix destroy for developer
=> update: destroy-developer

app/controllers/developers_controller.rb, app/models/developer.rb, app/views/developers/index.html.slim
**Describe**
- Fix destroy developer bug
- Fix filter bug
=> Fix: bug-filter

app/controllers/clients_controller.rb, app/controllers/projects_controller.rb, app/controllers/teches_controller.rb, app/helpers/clients_helper.rb, app/models/client.rb, app/models/project.rb, app/views/clients/_form.html.slim, app/views/clients/edit.html.slim, app/views/clients/index.html.slim, app/views/clients/new.html.slim, app/views/clients/show.html.slim, app/views/layouts/application/_left_menu.html.slim, app/views/projects/_form.html.slim, app/views/projects/index.html.slim, app/views/teches/index.html.slim, config/routes.rb, db/migrate/20210726141643_create_clients.rb, db/migrate/20210726171222_add_client_to_projects.rb, db/migrate/20210726182129_add_new_column_to_projects.rb, db/migrate/20210726182734_add_website_to_projects.rb, db/schema.rb, spec/factories/clients.rb, spec/factories/projects.rb, spec/models/client_spec.rb, spec/models/developer_spec.rb, spec/models/project_spec.rb, spec/requests/clients_spec.rb
**Describe**
- Filter technologies by technology type (frontend, backend, db)
- Filter projects by development type (mobile, website)
- Add client
- Add start_date, deployment, development type, website column to projects
- Search clients by name and headquarters, projects by name and deployment type
- Show all projects of a client when show a client
- Trello: https://trello.com/c/MCi5pkUs/788-update-admin-goldenowl
=> update: client-projects-teches

app/controllers/clients_controller.rb, app/models/client.rb, app/views/clients/index.html.slim, app/views/clients/show.html.slim, db/migrate/20210802201557_add_nationality_to_clients.rb, db/schema.rb, spec/factories/clients.rb, spec/models/client_spec.rb
**Describe**
- Add 1 column client's nationality base on address country
=> Create: client-nationality

app/controllers/projects_controller.rb, app/models/project.rb, app/views/projects/_form.html.slim, app/views/projects/index.html.slim, app/views/projects/show.html.slim, db/migrate/20210804140157_add_industry_to_projects.rb, db/schema.rb, spec/factories/projects.rb, spec/models/project_spec.rb
**Describe**
- Filter project by industry
- Filter project by development type
- Loom : https://www.loom.com/share/211721e50d794475931e930d5801ea72
=> Feat: filter-project

app/models/project.rb
**Describe**
- Update more industry
=> update: industry

app/controllers/projects_controller.rb, app/models/development_type.rb, app/models/project.rb, app/views/projects/_form.html.slim, app/views/projects/index.html.slim, app/views/projects/show.html.slim, db/migrate/20210805172032_create_development_types.rb, db/migrate/20210805175842_create_development_types_projects.rb, db/migrate/20210805183744_remove_development_type_from_project.rb, db/schema.rb, db/seeds.rb, spec/factories/development_types.rb, spec/factories/projects.rb, spec/models/development_type_spec.rb, spec/models/project_spec.rb
**Describe**
- Fix filter development-type (Select multiple development_type)
**Video**
https://www.loom.com/share/a02b8eb17beb47b7860af9f4d46ba8d6?focus_title=1&muted=1&from_recorder=1
=> Fix: filter-development-projects

app/views/projects/show.html.slim
**Describe**
- Add s to development_type
=> fix: detail-project

app/views/projects/show.html.slim
**Describe**
- Update project detail (Add management is PC list, fix developer list: Only display developer have that current project)
=> update: project-detail

app/javascript/stylesheets/application.scss, app/javascript/stylesheets/application/left_menu.scss, app/models/university.rb, app/views/layouts/application/_left_menu.html.slim
=> Left menu/setting

app/assets/javascripts/tools.coffee, app/assets/stylesheets/tools.scss, app/controllers/tools_controller.rb, app/helpers/tools_helper.rb, app/models/tool.rb, app/views/layouts/application/_left_menu.html.slim, app/views/tools/_form.html.slim, app/views/tools/edit.html.slim, app/views/tools/index.html.slim, app/views/tools/new.html.slim, app/views/tools/show.html.slim, config/routes.rb, spec/helpers/tools_helper_spec.rb, spec/requests/tools_request_spec.rb
create view and controller for tool
=> create view and controller for tool

app/assets/javascripts/certificates.coffee, app/assets/stylesheets/certificates.scss, app/controllers/certificates_controller.rb, app/helpers/certificates_helper.rb, app/models/certificate.rb, app/views/certificates/_form.html.slim, app/views/certificates/edit.html.slim, app/views/certificates/index.html.slim, app/views/certificates/new.html.slim, app/views/certificates/show.html.slim, app/views/layouts/application/_left_menu.html.slim, config/routes.rb, spec/helpers/certificates_helper_spec.rb, spec/requests/certificates_request_spec.rb
create view and controller certificate
=> create view and controller of certificate

app/javascript/stylesheets/application.scss, app/javascript/stylesheets/application/common.scss, app/views/certificates/index.html.slim, app/views/frameworks/index.html.slim, app/views/programming_languages/index.html.slim, app/views/tools/index.html.slim, app/views/universities/index.html.slim
Add action(edit/delete/show) in table view
=> UI/left menu/setting

app/controllers/skill_categories_controller.rb, app/helpers/skill_categories_helper.rb, app/models/skill_category.rb, app/views/layouts/application/_left_menu.html.slim, app/views/skill_categories/_form.html.slim, app/views/skill_categories/edit.html.slim, app/views/skill_categories/index.html.slim, app/views/skill_categories/new.html.slim, app/views/skill_categories/show.html.slim, config/routes.rb
=> CRUD model SkillCategory

app/controllers/skills_controller.rb, app/helpers/skills_helper.rb, app/models/skill.rb, app/views/layouts/application/_left_menu.html.slim, app/views/skills/_form.html.slim, app/views/skills/edit.html.slim, app/views/skills/index.html.slim, app/views/skills/new.html.slim, app/views/skills/show.html.slim, config/routes.rb
=> CRUD model Skill

app/controllers/concerns/resize_image.rb, app/controllers/contacts_controller.rb, app/models/contact.rb, app/views/contacts/_form.html.slim, app/views/contacts/index.html.slim, app/views/contacts/show.html.slim, config/application.rb
=> Update logic CRUD contact

app/controllers/developers_controller.rb, app/controllers/interns_controller.rb, app/javascript/stylesheets/application/common.scss, app/models/developer.rb, app/views/careers/index.html.slim, app/views/clients/index.html.slim, app/views/developers/_form.html.slim, app/views/developers/detail.html.slim, app/views/developers/index.html.slim, app/views/interns/_form.html.slim, app/views/interns/index.html.slim, app/views/post_categories/index.html.slim, app/views/posts/index.html.slim, app/views/project_coordinators/index.html.slim, app/views/projects/index.html.slim
Fix logic CRUD model Intern, Developer and update layout
=> Fix logic for model Intern, Developer and update layout

app/assets/javascripts/skill_category_groups.coffee, app/assets/stylesheets/skill_category_groups.scss, app/controllers/frameworks_controller.rb, app/controllers/skill_category_groups_controller.rb, app/controllers/tools_controller.rb, app/helpers/skill_category_groups_helper.rb, app/views/frameworks/index.html.slim, app/views/frameworks/show.html.slim, app/views/layouts/application/_left_menu.html.slim, app/views/skill_category_groups/_form.html.slim, app/views/skill_category_groups/edit.html.slim, app/views/skill_category_groups/index.html.slim, app/views/skill_category_groups/new.html.slim, app/views/skill_category_groups/show.html.slim, app/views/tools/_form.html.slim, app/views/tools/index.html.slim, app/views/tools/show.html.slim, config/routes.rb, spec/helpers/skill_category_groups_helper_spec.rb, spec/requests/skill_category_groups_request_spec.rb
CRUD for model skill category grou
p
=> CRUD for model skill category group

app/controllers/clients_controller.rb, app/controllers/employees_controller.rb, app/javascript/packs/employee.js, app/views/clients/_form.html.slim, app/views/clients/show.html.slim, app/views/employees/_form.html.slim, app/views/employees/index.html.slim, app/views/employees/show.html.slim, app/views/posts/show.html.slim, config/routes.rb
=> Add map for address

app/views/developers/project_histories/_list_project_histories.html.slim
=> fix set value in simple_form

app/views/developers/project_histories/_list_project_histories.html.slim
=> fix set value form project history

config/environments/production.rb
Change public_file_server.enabled = true in produce.rb
=> public_file_server.enabled = true

app/views/layouts/application.html.slim
delete stylesheet_link_tag in application.html.slim
=> Remove stylesheet_link_tag
